In [2]:
import time

In [4]:
import numpy as np
import time

#lets declare the size
Size = 1000000

#creating two lists
list1 = range(Size)
list1

range(0, 1000000)

In [8]:
list2 = range(Size)

#creatinh 2 numpy arrays
arr1 = np.arange(Size)
arr2 = np.arange(Size)

print(arr1)
print(arr2)

[     0      1      2 ... 999997 999998 999999]
[     0      1      2 ... 999997 999998 999999]


In [9]:
#calculating time for python list
start = time.time()
result1 = [(x + y) for x, y in zip(list1, list2)]
print("Time for python List in msec: ", (time.time() - start))

Time for python List in msec:  0.23662304878234863


In [10]:
#calculating time for numpy array
start = time.time()
result2 = (arr1 + arr2)
print(result2)

[      0       2       4 ... 1999994 1999996 1999998]
